-- ============================================================================
--  SIGMA_CHAT_RLS_v2.sql   —   RECORD OF A CHANGE ALREADY APPLIED TO PRODUCTION
--  §CHAT-HINT (v2.297)      —   project cimgpycjczatjzltgscf, 2026-08-01
--  DO NOT RE-RUN BLINDLY. This documents what was done and how to verify it.
-- ============================================================================
--
--  THE FAULT
--  ---------
--  public.messages had exactly ONE RLS policy:
--
--      sigma_anon_chat_all   FOR ALL   TO anon   USING (true)   WITH CHECK (true)
--
--  A policy bound `TO anon` does not apply to role `authenticated`. There was no
--  policy for `authenticated` on this table at all, so RLS refused that role
--  everything — SELECT as well as INSERT. Confirmed read-only against the live
--  database before the fix:
--
--      set local role anon;           select count(*) from public.messages;  -> 2
--      set local role authenticated;  select count(*) from public.messages;  -> 0
--
--  Effect: staff signed in through Supabase Auth (role `authenticated`) could
--  neither read nor post. Staff signed in locally — anon key, no session, so
--  role `anon` — worked perfectly. Same build, same payload, opposite outcome.
--  Presence kept working for everyone throughout, because Realtime presence is
--  broadcast and is never checked against table RLS, which made the panel look
--  healthy while it was not.
--
--  Corroborating forensic detail: messages_id_seq stood at 16 while only ids 1
--  and 2 existed. RLS WITH CHECK is evaluated after the identity value has been
--  assigned, so each refused INSERT still burned one. The 14 missing ids are 14
--  well-formed inserts that reached Postgres and were rejected at the policy
--  gate — not client-side failures, and not a stale build.
--
--  Compare public.orders, which has always worked for everybody: its
--  `app all orders` policy covers {authenticated, anon}.
--
--
--  WHAT WAS APPLIED (additive; the existing anon policy was left untouched)
--  -----------------------------------------------------------------------
--      create policy sigma_chat_authenticated
--        on public.messages for all to authenticated
--        using (true) with check (true);
--      -- plus table grants to authenticated, anon
--
--  A follow-up audit of every table in `public` for the same anon-only gap found
--  one more — public.inquiries, where website enquiries were invisible to any
--  cloud-signed-in user — and it received the same treatment. A re-audit is
--  clean. The three counter tables (order_number_counters, receipt_counters,
--  statement_counters) intentionally have NO policies: they are reached only
--  through SECURITY DEFINER RPCs so that clients cannot rewind a sequence.
--  Those were deliberately left alone and must stay that way.
--
--
--  NO CLIENT-SIDE WORKAROUND IS USED
--  ---------------------------------
--  Team Chat talks to the database through the ordinary `_sb` client exactly as
--  it always has. v2.297 changes only how failures are REPORTED (§CHAT-HINT):
--  the old text blamed a missing table and told the reader to run
--  "SIGMA_CHAT_TABLE_v1.sql", a file that does not exist in this repository —
--  which sent the diagnosis in the wrong direction for the whole life of the
--  bug. Refusals are now named for what they are.
--
--
--  VERIFY (read-only)
--  ------------------
--    select policyname, roles::text, cmd from pg_policies
--      where schemaname='public' and tablename='messages';
--    -- expect: sigma_anon_chat_all {anon}, sigma_chat_authenticated {authenticated}
--
--    set local role authenticated; select count(*) from public.messages;  -- > 0
--
--  Re-audit for the same gap anywhere else in public:
--    select c.relname
--      from pg_class c join pg_namespace n on n.oid=c.relnamespace
--     where n.nspname='public' and c.relkind='r' and c.relrowsecurity
--       and not exists (select 1 from pg_policies p
--                        where p.schemaname='public' and p.tablename=c.relname
--                          and 'authenticated' = any(p.roles));
--    -- expect only the three counter tables, which are SECURITY DEFINER by design
-- ============================================================================
