#!/bin/sh
# SIGMA cam-archiver — installer for a Synology NAS (DSM 7). No Docker.
#
# Run over SSH, as your normal DSM user, from the folder this file is in:
#     sh install.sh
#
# What it does:
#   - installs `uv` (a standalone Python manager) into ~/.local/bin
#   - installs Python 3.12 for your user only (DSM ships 3.9; blinkpy needs 3.10+)
#   - creates a private venv in ~/.cam-archiver with blinkpy + ring_doorbell
#   - writes run.sh next to this file, for DSM Task Scheduler
# It changes nothing system-wide and needs no root.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
SECRETS="${CAM_ARCHIVER_HOME:-$HOME/.cam-archiver}"

if [ -z "$HOME" ] || [ ! -d "$HOME" ] || [ ! -w "$HOME" ]; then
  echo
  echo "Your DSM home folder is missing or not writable."
  echo "Enable it: Control Panel > User & Group > Advanced > User Home > Enable user home service."
  echo "Then run  sh install.sh  again."
  exit 1
fi

echo "NAS CPU: $(uname -m)   share folder: $HERE"
mkdir -p "$SECRETS"
chmod 700 "$SECRETS"

UV="$HOME/.local/bin/uv"
if [ ! -x "$UV" ]; then
  echo "Installing uv into $HOME/.local/bin ..."
  curl -LsSf https://astral.sh/uv/install.sh | env UV_NO_MODIFY_PATH=1 sh
fi

echo "Installing Python 3.12 (user-only) ..."
"$UV" python install 3.12
"$UV" venv --allow-existing --python 3.12 "$SECRETS/venv"
echo "Installing blinkpy + ring_doorbell ..."
"$UV" pip install --python "$SECRETS/venv/bin/python" -r "$HERE/requirements.txt"

cat > "$HERE/run.sh" <<EOF
#!/bin/sh
# Generated by install.sh — the command DSM Task Scheduler runs every 15 minutes.
export CAM_ARCHIVER_HOME="$SECRETS"
exec "$SECRETS/venv/bin/python" "$HERE/archiver.py" run
EOF
chmod +x "$HERE/run.sh"

echo
"$SECRETS/venv/bin/python" "$HERE/archiver.py" status
echo
echo "Installed. Next:"
echo "  $SECRETS/venv/bin/python $HERE/archiver.py login-blink"
echo "  $SECRETS/venv/bin/python $HERE/archiver.py login-ring"
echo "  sh $HERE/run.sh          (first run copies the last 30 days — can take a while)"
echo "Then add the Task Scheduler job (see README.md)."
